[tool.pylint.checker]
extension-pkg-allow-list = ["lxml"]
fail-under = 9.41
ignore-patterns = [".*_test.py"]

[tool.pylint.similarities]
min-similarity-lines=7

[tool.pytest.ini_options]

[tool.flake8]
max-line-length = 127
